<a href="https://colab.research.google.com/github/Priyagane/Pandas/blob/main/Pandas_Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[8 7 5 9]
 [4 3 8 9]
 [6 9 8 6]]
[[9 7 5]
 [5 2 3]
 [7 3 2]
 [3 7 4]]


In [38]:
a.dot(b)

array([[169, 148, 107],
       [134, 121,  81],
       [173, 126,  97]])

In [39]:
np.dot(a,b)

array([[169, 148, 107],
       [134, 121,  81],
       [173, 126,  97]])

In [40]:
dataset = pd.read_csv('/content/data.csv')
dataset.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

In [41]:
dataset.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [42]:
dataset.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [43]:
dataset.columns

Index(['OBJECTID', 'UNIT_NAME', 'DESCRIPTION', 'ACRES', 'SHAPE.AREA',
       'SHAPE.LEN'],
      dtype='object')

In [44]:
dataset.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [45]:
dataset.groupby('DESCRIPTION')['OBJECTID', 'UNIT_NAME',  'ACRES', 'SHAPE.AREA',
       'SHAPE.LEN'].mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [46]:
dataset.sample(10)


OBJECTID                                   UNIT_NAME  \
19        40  Head of the Mountain State Nature Preserve   
7         28                  Lewis and Clark State Park   
17        38         Fahlgren Park State Recreation Area   
20        41           Missouri River State Natural Area   
0         21                   Fort Stevenson State Park   
13        36       Crow Flies High State Recreation Area   
5         26                        Icelandic State Park   
16        37                  Elkhorn State Natural Area   
14        33                     Turtle River State Park   
1         22                      Beaver Lake State Park   

              DESCRIPTION   ACRES  SHAPE.AREA  SHAPE.LEN  
19  State Nature Preserve   72.30    0.000034   0.033885  
7              State Park  524.81    0.000256   0.130420  
17  State Recreation Area   21.56    0.000010   0.013294  
20     State Natural Area  174.39    0.000083   0.087192  
0              State Park  586.48    0.000284   0.135641  
13  State Recreation Area  247.11    0.000120   0.050518  
5              State Park  930.30    0.000461   0.166712  
16     State Natural Area  264.84    0.000127   0.067082  
14             State Park  775.28    0.000378   0.145220  
1              State Park  273.16    0.000129   0.080067

In [47]:
data = pd.DataFrame(np.random.random(10))
dataset['New_feature'] = data


In [48]:
dataset.OBJECTID.isnull().sum()

0

In [50]:
dataset.loc[0,'OBJECTID']=dataset.OBJECTID.mean()
dataset.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0     33.48        Fort Stevenson State Park  State Park  586.48    0.000284   
1     22.00           Beaver Lake State Park  State Park  273.16    0.000129   
2     23.00  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3     24.00           Fort Ransom State Park  State Park  933.78    0.000444   
4     25.00        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  New_feature  
0   0.135641     0.852873  
1   0.080067     0.113672  
2   0.119868     0.480224  
3   0.128733     0.573346  
4   0.125546     0.719765